type: repackage
arch: all
layer_cache: true

produces:
  - omakasui-core-archive-keyring

publications:
  omabuntu:
    produces:
      - omakasui-core-archive-keyring
  omadeb:
    produces:
      - omakasui-core-archive-keyring
  omari:
    produces:
      - omakasui-core-archive-keyring
