type: repackage
arch: all
layer_cache: true

produces:
  - omakasui-nvim
  - omakub-nvim
  - omadeb-nvim

publications:
  omabuntu:
    produces:
      - omakasui-nvim
      - omakub-nvim
  omadeb:
    produces:
      - omakasui-nvim
      - omadeb-nvim
