type: repackage
arch: all
layer_cache: true

produces:
  - omakasui-devtools
  - omakub-devtools
  - omadeb-devtools

publications:
  omabuntu:
    produces:
      - omakasui-devtools
      - omakub-devtools
  omadeb:
    produces:
      - omakasui-devtools
      - omadeb-devtools
